"""Cross-language agreement proof.

Loads the 192 test vectors generated by the canonical TypeScript engine and
asserts the Python ``solve`` reproduces every ``groundTruth`` exactly. The TS
engine is canonical: any disagreement is a bug in the Python re-implementation.
"""

import json
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from geometry import solve  # noqa: E402

VECTORS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "test-vectors.json",
)

with open(VECTORS_PATH) as f:
    _DATA = json.load(f)

CASES = _DATA["cases"]


def test_vector_count():
    assert _DATA["count"] == 192
    assert len(CASES) == 192


@pytest.mark.parametrize("case", CASES, ids=[
    f"{c['type']}-{c['relationship']}-incl{c['inclination']}-{c['givenAngle']}to{c['askAngle']}"
    for c in CASES
])
def test_python_agrees_with_typescript(case):
    result = solve(
        inclination=case["inclination"],
        parallel=case["parallel"],
        relationship=case["relationship"],
        given_angle=case["givenAngle"],
        ask_angle=case["askAngle"],
        given_value=case["givenValue"],
    )
    expected = case["groundTruth"]

    if expected is None:
        assert result is None, (
            f"Expected None (rule does not apply) but got {result} for {case}"
        )
    else:
        assert result is not None, f"Expected {expected} but got None for {case}"
        assert result == pytest.approx(expected, abs=1e-6), case
